# Generated by Django 4.1.7 on 2023-03-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0004_alter_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='utc_time',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
