# Generated by Django 4.1.7 on 2023-03-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='promo',
            unique_together={('title', 'cafe')},
        ),
    ]
