# Generated by Django 4.1.7 on 2023-03-31 05:10

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_city_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='utc_time',
            field=timezone_field.fields.TimeZoneField(use_pytz=True),
        ),
    ]
