# Generated by Django 4.1.7 on 2023-04-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_promo_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
