# Generated by Django 4.1.7 on 2023-04-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_promo_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.promo',),
        ),
    ]
